# Site settings
name: Benedikt Ritter
description: "Software Crafter, Apache Member, Open Development Enthusiast"
url: "http://www.benediktritter.de"


# Delete the lines you don't need
github_username:  britter
mastodon_homeserver: chaos.social
mastodon_username: britter
linkedin_username: benedikt-ritter-83847b84

avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars1.githubusercontent.com/u/1327662"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"

# Build settings
markdown: kramdown
permalink: pretty
